### ISSUE TITLE
DataFrame Append

### ISSUE THREAD

**Issue by ebrown91** [mvgorcum/Sessile.drop.analysis#13]
Running the sample video provided 
raspberrypi@raspberrypi:~ $ drop_analysis
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/raspberrypi/.local/lib/python3.9/site-packages/drop_analysis/gui.py", line 113, in _updateFitHeightLine
    _,basearray=self.BaseLine.getArrayRegion(self.VideoItem.image, self.VideoItem, returnSlice=False, returnMappedCoords=True)
  File "/home/raspberrypi/.local/lib/python3.9/site-packages/pyqtgraph/graphicsItems/ROI.py", line 2208, in getArrayRegion
    rgn = fn.affineSlice(data, shape=(int(d.length()),), vectors=[Point(d.norm())], origin=o, axes=axes, order=order, returnCoords=returnMappedCoords, **kwds)
  File "/home/raspberrypi/.local/lib/python3.9/site-packages/pyqtgraph/functions.py", line 809, in affineSlice
    trAx = list(range(data.ndim))
AttributeError: 'NoneType' object has no attribute 'ndim'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/raspberrypi/.local/lib/python3.9/site-packages/drop_analysis/gui.py", line 235, in RunAnalysis
    self.MeasurementResult=self.MeasurementResult.append(results,ignore_index=True)#append depreciated changed to concat
  File "/home/raspberrypi/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by mvgorcum** [comment]
Thanks for your report! The next version will fix this issue. If you want to get a working version now you can install from the master branch.

**Comment by mvgorcum** [comment]
With [v1.0.0rc1](https://github.com/mvgorcum/Sessile.drop.analysis/releases/tag/v1.0.0rc1) this issue is fixed.
