### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Ammar353** [mvgorcum/Sessile.drop.analysis#14]
pip install drop_analysis
Collecting drop_analysis
  Using cached drop-analysis-1.0.0rc2.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [122 lines of output]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'Description-Content-Type' will not be supported in future
              versions. Please use the underscore name 'Description_Content_Type' instead.

              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\dist.py:473: SetuptoolsDeprecationWarning: Invalid uppercase configuration
      !!

              ********************************************************************************
              Usage of uppercase key 'Description_Content_Type' in 'metadata' will not be supported in
              future versions. Please use lowercase 'description_content_type' instead.

              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.make_option_lowercase(opt, section)
      C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py:75: _MissingDynamic: `scripts` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `scripts = ['drop_analysis = drop_analysis.__main__:main']`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `scripts` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `scripts` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py:75: _MissingDynamic: `dependencies` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `dependencies = ['numpy', 'pandas', 'scipy', 'pyqt5', 'opencv-python-headless', 'openpyxl', 'fast-histogram', 'lsq-ellipse', 'imageio', 'shapely', 'pyqtgraph >=0.11.0', 'toml', 'h5py', 'appdirs']`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `dependencies` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `dependencies` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py:75: _MissingDynamic: `optional-dependencies` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `optional-dependencies = {'test': ['pytest']}`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `optional-dependencies` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `optional-dependencies` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py:82: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
        corresp(dist, value, root_dir)
      Traceback (most recent call last):
        File "C:\Users\ammar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.10)\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ammar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.10)\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\ammar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.10)\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "C:\Users\ammar\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.10)\lib\site-packages\_virtualenv.py", line 23, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 67, in apply_configuration
          return _apply(dist, config, filepath)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py", line 56, in apply
          _apply_project_table(dist, config, root_dir)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py", line 82, in _apply_project_table
          corresp(dist, value, root_dir)
        File "C:\Users\ammar\AppData\Local\Temp\pip-build-env-xnomhu1g\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py", line 223, in _optional_dependencies
          dist.extras_require = {**existing, **val}
      TypeError: 'list' object is not a mapping
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mvgorcum** [comment]
Thanks for the report! I'm currently ill, but I'll look in to it as soon as I have some time.

**Comment by mvgorcum** [comment]
I haven't been able to reproduce this, is this still a problem?
