### ISSUE TITLE
ImageReader error

### ISSUE THREAD

**Issue by floooreeent** [mvgorcum/Sessile.drop.analysis#15]
Hi, I have an issue with the software: I can't import pictures. 

Whenever I try to open a picture, I get this message in the Terminal:
 
`Traceback (most recent call last):
  File "C:\PROGRA~2\DROPAN~1\drop_analysis\gui.py", line 177, in openCall
  File "C:\PROGRA~2\DROPAN~1\drop_analysis\FrameSupply.py", line 152, in start
  File "C:\PROGRA~2\DROPAN~1\imageio\core\functions.py", line 98, in get_reader
  File "C:\PROGRA~2\DROPAN~1\imageio\core\imopen.py", line 277, in imopen
ValueError: Could not find a backend to open `C:/Users/me/Desktop/goutte.png`` with iomode `r?`.
Based on the extension, the following plugins might add capable backends:
  pillow:  pip install imageio[pillow]
  PNG-PIL:  pip install imageio[pillow]
  PNG-FI:  pip install imageio[freeimage]
  ITK:  pip install imageio[simpleitk]`

And when I try again, this happens:

`Traceback (most recent call last):
  File "C:\PROGRA~2\DROPAN~1\drop_analysis\gui.py", line 165, in openCall
  File "C:\PROGRA~2\DROPAN~1\drop_analysis\FrameSupply.py", line 160, in stop
AttributeError: 'ImageReader' object has no attribute 'IOReader'`

I installed the software with the installer (and also with pip via anaconda) and I don't understand why it doesn't work.

(Sorry I'm new here I don't know if I should post this here, please excuse me if I shouldn't have)

**Comment by mvgorcum** [comment]
Apologies for missing this issue for so long. It seems like github didn't feel like e-mailing me about it. :(

The new v1.0.0rc2 release should fix this issue. If you still run into this problem please let me know!
