### ISSUE TITLE
Camera capture fails with compile binary

### ISSUE THREAD

**Issue by mvgorcum** [mvgorcum/Sessile.drop.analysis#6]
Reported in the matrix room:

```
Traceback (most recent call last):
  File "QT_sessile_drop_analysis.py", line 135, in CameraToggle
  File "FrameSupply.py", line 170, in getframesize
AttributeError: 'OpencvCamera' object has no attribute 'cap'
```

**Comment by mvgorcum** [comment]
Fixed with 0.2.0 beta.
